name: TMDC Docker Image CI workflow

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - '*/*[0-9]+.*[0-9]+.*[0-9]*'
  #     - '*/*[0-9]+.*[0-9]+.*[0-9]+'

jobs:
# For DEV RELEASE

  dev-release:
    name: Dev release Package and Push Helm Chart to ECR
    runs-on: ubuntu-latest
    container:
        image: rubiklabs/k8s_cli_builder:0.4.0
        credentials:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    permissions:
      id-token: write
      contents: read
    
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-')
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::387694172318:role/github_action-helm-push-to-ecr
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Package and push Helm chart
      env:
        TAG: ${{ github.ref_name }}
        ECR_HOST: ${{ steps.login-ecr-public.outputs.registry }}
      run: make push-chart  

# For PUBLIC RELEASE

  public-release:
    name: Public Package and Push Helm Chart to ECR
    runs-on: ubuntu-latest
    container:
        image: rubiklabs/k8s_cli_builder:0.4.0
        credentials:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    permissions:
      id-token: write
      contents: read        
    
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-')
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::387694172318:role/github_action-helm-push-to-ecr
            aws-region: us-west-2
    
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          
        - name: Package and push Helm chart
          env:
            TAG: ${{ github.ref_name }}
            ECR_HOST: ${{ steps.login-ecr-public.outputs.registry }}
          run: make push-chart