{{- if .Values.auth.authentication.enabled }}
{{- if eq .Values.auth.authentication.provider "heimdall" }}
{{- if .Values.auth.superUsers -}}
{{- if and .Values.auth.superUsers.broker .Values.auth.superUsers.brokerApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-token-{{ .Values.auth.superUsers.broker }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
type: Opaque
data:
  APIKEY: {{ .Values.auth.superUsers.brokerApiKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}