{{- if .Values.storageOffload }}
{{- if eq .Values.storageOffload.driver "google-cloud-storage" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.storageOffload.gcsServiceAccountSecret}}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.broker.component }}
type: Opaque
data:
  {{ .Values.storageOffload.gcsServiceAccountJsonFile }}: {{ .Values.storageOffload.gcsServiceAccountJsonFileContent }}
---
{{- end }}
{{- end }}