
{{- if and .Values.rbac.enabled .Values.components.pulsar_heartbeat }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}"
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}"
  namespace: {{ template "pulsar.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}"
subjects:
- kind: ServiceAccount
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}"
  namespace: {{ template "pulsar.namespace" . }}
{{- end }}
