{{- if and .Values.components.pulsar_heartbeat .Values.pulsar_heartbeat.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ .Values.pulsar_heartbeat.component }}
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_heartbeat.component }}
spec:
  jobLabel: {{ .Values.pulsar_heartbeat.component }}
  selector:
    matchLabels:
      component: {{ .Values.pulsar_heartbeat.component }}
  namespaceSelector:
    matchNames:
      - {{ template "pulsar.namespace" . }}
  {{- if .Values.pulsar_heartbeat.serviceMonitor.endpoints }}
  endpoints:
{{ toYaml .Values.pulsar_heartbeat.serviceMonitor.endpoints | indent 2 }}
  {{- end }}
{{- end }}