{{- if and .Values.components.proxy .Values.proxy.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: {{ .Values.proxy.component }}
  name: {{ template "pulsar.fullname" . }}-{{ .Values.proxy.component  }}
spec:
  endpoints:
  {{- with .Values.proxy.serviceMonitor }}
  - interval: {{ .interval }}
    scrapeTimeout: {{ .scrapeTimeout }}
    port: {{ .port }}
    scheme: {{ .scheme }}
    tlsConfig:
      insecureSkipVerify: true
      {{- if .certs.enabled }}
      caFile: {{ .certs.caFile }}
      keyFile: {{ .certs.keyFile }}
      certFile: {{ .certs.certFile }}
      {{- end }}
    {{- if .authorization.enabled }}
    bearerTokenSecret:
      name: {{ .authorization.secretName }}
      key: {{ .authorization.secretKeyName }}
    {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      component: {{ .Values.proxy.component }}
{{- end }}