{{- if and .Values.components.zookeeper .Values.zookeeper.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: {{ .Values.zookeeper.component }}
  name: {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}
spec:
  endpoints:
  {{- with .Values.zookeeper.serviceMonitor }}
  - interval: {{ .interval }}
    scrapeTimeout: {{ .scrapeTimeout }}
    {{- if .https.enabled }}
    port: {{ .https.port }}
    scheme: {{ .https.scheme }}
    tlsConfig:
      insecureSkipVerify: true
      {{- if .https.certs.enabled }}
      caFile: {{ .https.certs.caFile }}
      keyFile: {{ .https.certs.keyFile }}
      certFile: {{ .https.certs.certFile }}
      {{- end }}
    {{- else }}
    port: {{ .port }}
    {{- end }}
    {{- if .authorization.enabled }}
    bearerTokenSecret:
      name: {{ .authorization.secretName }}
      key: {{ .authorization.secretKeyName }}
    {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      component: {{ .Values.zookeeper.component }}
{{- end }}